### ISSUE TITLE
Resource to find a club affiliations

### ISSUE THREAD

**Issue by julaudo** [alexeil/sikb-api#14]
### Description:
**As a** user having CLUB_AFFILIATIONS_READ right on a club
**I want** to be able to see all club affiliations
**So that** I can check information of previous years

### Actual situation: 
The only way to load affiliations is to call /clubs/{clubId}/seasons/{seasonId}/affiliations. That would need one call per season

### Target situation:
/clubs/{clubId}/affiliations returns all the club affiliations

### Acceptance criteria:
- [x] The resource returns all the club affiliations
- [x]  The resource is allowed only if the user has CLUB_AFFILIATIONS_READ right on the club

**Comment by alexeil** [comment]
A new API is created : "GET /clubs/{clubId}/affiliations"

returning an array of : 
    seasonWithAffiliation:
      properties:
        season:
          $ref: '#/components/schemas/season'
        affiliation:
          $ref: '#/components/schemas/affiliation'

**Comment by alexeil** [comment]
For now this is a really simple functionality management so the get affiliations is binding with the right CLUB_READ
