### ISSUE TITLE
Resources access control

### ISSUE THREAD

**Issue by julaudo** [alexeil/sikb-api#15]
**Is your feature request related to a problem? Please describe.**
Currently all resources are allowed for every users. Access control should be implemented, so unauthorized access will result in a 403 error.

**Describe the solution you'd like**
A simple solution would be to make the mackend handle for each user
- A list of allowed functionalities (CLUB_CREATE, CLUB_UPDATE, CLUB_AFFILIATION_CREATE, ...)
- A list of clubs for which the user has rights (list of technical ids)

In this solution, the user will have the same rights on all the clubs on which he has rights.

**Describe alternatives you've considered**
If necessary, a more complex model can be implemented, in which a user will possibly have differents rights on some clubs (for example read club A's affiliations and edit club B's affiliations).
This is a structural choice so we need to think about most convenient solution.

**Additional context**
A notion of profile could simplify users management in backend side. A profile would be a list of functionalities, so a user would be linked to
- One or more profiles -> a list of functionalities
- One or more clubs

This notion of profile don't need to be visible in the swagger. Except if we want to make it appear in the website.

**Comment by alexeil** [comment]
For now there is no need of different right by clubs.

I decided to implement as requested : 
A user has a profile and its profile has a list of allowed functionalities and a list of clubs
