### ISSUE TITLE
Board model is not canonical

### ISSUE THREAD

**Issue by julaudo** [alexeil/sikb-api#16]
**Application version**
1.0.0-RC5

**Describe the bug**
Board model is not canonical

**To Reproduce**
Look at swagger specification
Board model is as follows:
```
{
    president: string;
    presidentSex: Sex;
    secretary: string;
    secretarySex: Sex;
    treasurer: string;
    treasurerSex: Sex;
    membersNumber: number;
    electedDate: string;
 }
```

**Expected behavior**

Person type could be used, but some required fields may be anwanted. In this case, create a new type, eg PersonWithSex.

Board becomes:

```
Board model is as follows:
{
    president: PersonWithSex;
    secretary: PersonWithSex;
    treasurer: PersonWithSex;
    membersNumber: number;
    electedDate: string;
 }
```

**Comment by alexeil** [comment]
As required a new structure was created : 
    boardMember:
      required:
        - name
        - sex
      properties:
        name:
          type: string
          maxLength: 255
        sex:
          $ref: '#/components/schemas/sex'
