### ISSUE TITLE
Affiliation creation causes 500 Internal Server Error

### ISSUE THREAD

**Issue by julaudo** [alexeil/sikb-api#17]
**Application version**
1.0.0-RC5 …

**Describe the bug**
The following request causes 500 Internal Server Error

**To Reproduce**
cURL request:
`curl 'http://ec2-35-180-42-251.eu-west-3.compute.amazonaws.com:8080/sikb/api/v1/clubs/12/seasons/1/affiliations' -H 'Accept: application/json, text/plain, */*'  -H 'access_token: YWRmZDFiMWItMDEzMC00ZTA4LTg2NWYtODE5NWU0OGUxN2RmMjAxOS0wNC0zMFQxMTo1NzowNi42NTFa' -H 'Authorization: Basic YWRtaW46YWRtaW4=' -H 'Content-Type: application/json' --data-binary '{"prefectureNumber":"prefectureNumber","prefectureCity":"prefectureCity","siretNumber":"siretNumber","address":"address","postalCode":"35000","city":"RENNES","phoneNumber":"0612345678","email":"email","webSite":"webSite","board":{"president":"president2","presidentSex":"FEMALE","secretary":"secretary","secretarySex":"MALE","treasurer":"treasurer","treasurerSex":"FEMALE","membersNumber":3,"electedDate":"electedDate"},"id":1}' --compressed`

**Expected behavior**
Should return 201 created

**Comment by julaudo** [comment]
Same error seems to be present for all post requests

**Comment by alexeil** [comment]
The swagger wasn't respected in this case : "electedDate":"electedDate". Elected should be a date.

Even though this wasn't a bug, I will improve returned message to allow API consumer to help debugging errors.
