### ISSUE TITLE
Unexpected value 'M' while loading Affiliation

### ISSUE THREAD

**Issue by julaudo** [alexeil/sikb-api#18]
**Application version**
1.0.0-RC5

**Describe the bug**
After creating an affiliation, try to load it using get request. Then an error is thrown with body
`{"code":1,"message":"Unexpected value 'M'"}`

**To Reproduce**
cURL:
curl 'http://ec2-35-180-42-251.eu-west-3.compute.amazonaws.com:8080/sikb/api/v1/clubs/12/seasons/20182019/affiliations' -H 'Accept: application/json, text/plain, */*' -H 'access_token: MGNiMzE4NWItMTgwZC00ODIwLTk2MmYtYTViMjE2MDAwZTg1MjAxOS0wNC0zMFQxNDo0NDo0MS42Mjda' -H 'Authorization: Basic YWRtaW46YWRtaW4=' --compressed

**Expected behavior**
Should return 200 OK with affiliation in body.

**Comment by alexeil** [comment]
Test dataset was corrupted. There was an "M" instead of "MALE".
