### ISSUE TITLE
API does not check unicity during affiliation creation

### ISSUE THREAD

**Issue by julaudo** [alexeil/sikb-api#19]
**Application version**
version : 1.0.0-RC6

**Describe the bug**
POST an affiliation that already exists will create multiple versions of the same affiliation.

**To Reproduce**
Call multiple time the same post request to create an affiliation. API returns 200 OK even if an affiliation already exists.
Subsequent call to get /affiliations will return 500 Internal Server Error : "Key 20182019 is not unique in Result..."

**Expected behavior**
If an affiliation already exists for the season, API should return **409 Conflict**

**Comment by alexeil** [comment]
I will let the database controlling these kinds of issues. The API will return an error HTTP 500 with a body looking like :
{
    "code": 4,
    "message": "Database Error : ERROR: duplicate key value violates unique constraint \"constraint_name\"\n  Détail : Key (\"clubId\", season)=(12, 20182019) already exists."
}
